name: Train on MNIST dataset
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4.6.1
        with:
          python-version: '3.10'

      - name: Cache Python dependencies
        uses: actions/cache@v3.2.6
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train on MNIST Dataset
        run: python main.py configs/example.toml
