name: Train on MNSIT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4.6.1
        with:
          python-version: '3.10'

      - name: Cache Python dependencies
        uses: actions/cache@v3.2.6
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script and cache datasets directory
        run: |
          python main.py configs/example.toml
          mv datasets ${{ runner.workspace }}/datasets
        env:
          CACHE_KEY: ${{ runner.os }}-datasets-${{ hashFiles('${{ runner.workspace }}/datasets') }}

      - name: Cache datasets directory
        uses: actions/cache@v3.2.6
        with:
          path: ${{ runner.workspace }}/datasets
          key: ${{ env.CACHE_KEY }}
          restore-keys: ${{ runner.os }}-datasets-
